name = "glevenshtein"
version = "1.0.0"


description = "Calculate the levenshtein distance - in pure gleam!"
licences = ["MIT"]
repository = { type = "github", user = "MoeDevelops", repo = "glevenshtein" }
links = []

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
